---
service: example-service

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpackIncludeModules:
    forceInclude:
      - pg
      - source-map-support

  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 300
  deploymentBucket: example.com
  environment:
    NODE_ENV: ${opt:stage, self:custom.stage}
  vpc: ${file(../sls/vpc.yml):${self:custom.stage}}

functions:
  register:
    handler: index.handler
    events:
      - http: any /{proxy+}

resources:
  Resources:
    apiMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn: ExampleLambdaPermissionApiGateway
      Properties:
        BasePath: example
        DomainName: foo.bar.com
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: ${self:custom.stage}
    RegisterLogGroup:
      Properties:
        RetentionInDays: "7"
